import { Container, Theme } from '@radix-ui/themes';
import '@radix-ui/themes/styles.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import AuthProvider from './auth/provider';
import './globals.css';
import NavBar from './nav-bar';
import './theme-config.css';

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.variable}>
      <body>
        <AuthProvider>
        <Theme appearance="light" accentColor="iris">
          <NavBar />
          <main className="mx-auto max-w-7xl sm:px-6 lg:px-8"><Container>{children}</Container></main>
        </Theme>
        </AuthProvider>
      </body>
    </html>
  );
}
